# Generated by Django 2.2.3 on 2019-11-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_user_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='username',
        ),
        migrations.AddField(
            model_name='user_details',
            name='designations',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
