# Generated by Django 2.2.3 on 2019-11-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20191112_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='designations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designa', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='designations',
        ),
        migrations.AddField(
            model_name='user_details',
            name='email',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='role',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='username',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
