# Generated by Django 2.2.3 on 2019-11-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20191112_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=30)),
                ('from_time', models.CharField(max_length=30)),
                ('to_time', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='designations',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='role',
        ),
    ]
