# Generated by Django 2.2.3 on 2019-11-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20191113_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_details',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='doctor_details',
            name='to_time',
        ),
        migrations.AddField(
            model_name='doctor_details',
            name='login_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
