# Generated by Django 2.2.3 on 2019-11-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20191115_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='appoint_limit',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
