# Generated by Django 2.2.3 on 2019-11-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20191116_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ref_id', models.CharField(max_length=10)),
                ('doctor_ref_id', models.CharField(max_length=10)),
                ('week_id', models.CharField(max_length=10)),
            ],
        ),
    ]
