# Generated by Django 2.2.3 on 2019-11-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='login_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
