# Generated by Django 2.2.3 on 2019-11-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_user_details_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
