# Generated by Django 2.2.3 on 2019-11-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='week_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='diets_tips',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
