# Generated by Django 2.2.3 on 2019-11-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_auto_20191116_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
