# Generated by Django 2.2.3 on 2019-11-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='time_slots',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor_details',
            name='active_days',
            field=models.CharField(max_length=15),
        ),
    ]
