# Generated by Django 2.2.3 on 2019-11-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_auto_20191118_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='week_id',
            new_name='slot_id',
        ),
    ]
