# Generated by Django 2.2.3 on 2020-02-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_auto_20200211_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='regno',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor_details',
            name='place',
            field=models.CharField(max_length=150),
        ),
    ]
