# Generated by Django 2.2.3 on 2020-02-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_auto_20200212_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='photo',
            field=models.ImageField(default=1, upload_to='photo'),
            preserve_default=False,
        ),
    ]
