# Generated by Django 2.2.7 on 2020-03-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0023_doctor_details_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='specilizatin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specilization', models.CharField(max_length=20)),
            ],
        ),
    ]
