# Generated by Django 2.2.7 on 2020-03-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0027_rating_doc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(max_length=10)),
                ('cardno', models.CharField(max_length=10)),
            ],
        ),
    ]
